pretrained_model_path: "./stable-diffusion-v1-5"
output_dir: "./outputs/camera-boat"

train_data:
  video_path: "./data/camera_boat"
  prompt: "a DSLR camera resting by a window with a lake and green mountains in the background"
  n_sample_frames: 32
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  prompts:
    - "a DSLR camera by a train window, in the style of Studio Ghibli"
  video_length: 32
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 300
checkpointing_steps: 1000
validation_steps: 300
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
