pretrained_model_path: "./outputs/car"
image_path: "./data/car"
prompt: "a car is driving on the road"
prompts:
  - "a car is driving on the road"
  - "a futuristic car is driving on the road"
blend_word:
  - 'car'
  - 'car'
eq_params:
  words:
    - "futuristic"
  values:
    - 2
save_name: "car-futuristic"
is_word_swap: False