pretrained_model_path: "./outputs/eye-brown"
image_path: "./data/eye_brown"
prompt: "brown eye blinking"
prompts:
  - "brown eye blinking"
  - "crystal brown eye blinking"
blend_word:
  - 'eye'
  - 'eye'
eq_params:
  words:
    - "crystal"
  values:
    - 4
save_name: "eye_brown_crystal"
is_word_swap: False