pretrained_model_path: "./outputs/motorcycle-riding"
image_path: "./data/motorcycle_riding"
prompt: "motorcycle riding on the road with trees"
prompts:
  - "motorcycle riding on the road with trees"
  - "motorcycle riding on icy road with trees"
blend_word:
  - 'road'
  - 'road'
eq_params:
  words:
    - "icy"
  values:
    - 4
save_name: "motorcycle_riding_icy"
is_word_swap: False