pretrained_model_path: "./outputs/red-backpack"
image_path: "./data/red_backpack"
prompt: "man wearing a red backpack"
prompts:
  - "man wearing a red backpack"
  - "man wearing a blue backpack"
blend_word:
  - 'backpack'
  - 'backpack'
eq_params:
  words:
    - "blue"
  values:
    - 4
save_name: "red_backpack_blue"
is_word_swap: False