pretrained_model_path: "./outputs/white-cat"
image_path: "./data/white_cat"
prompt: "white cat is looking"
prompts:
  - "white cat is looking"
  - "ghost cat is looking"
blend_word:
  - 'cat'
  - 'cat'
eq_params:
  words:
    - "ghost"
  values:
    - 4
save_name: "white_cat_ghost"
is_word_swap: False