<script setup lang="ts">
	import Section from "~/components/Basic/Section.vue";
	import P from "~/components/Basic/P.vue";
	import H3 from "~/components/Basic/H3.vue";
	import { faEye, faClock, faLock } from "@fortawesome/free-solid-svg-icons";
	import A from "~/components/Basic/A.vue";
</script>

<template>
	<Section class="mt-40 text-gray-200 h-full">
		<div class="my-auto text-center flex flex-col gap-2">
			<H3 class="mb-2"> Welcome! </H3>
			<P>
				<font-awesome
					:icon="faEye"
					class="text-blue-400"
				/>
				This user study is designed to evaluate the quality of videos generated by various editing techniques
				using diffusion models.
			</P>
			<P>
				<font-awesome
					:icon="faClock"
					class="text-yellow-400"
				/>
				The process takes no more than 10 minutes and involves selecting the preferred video in a series of
				comparisons.
			</P>
			<P>
				<font-awesome
					:icon="faLock"
					class="text-green-400"
				/>
				No personal data is collected.
			</P>
			<P class="font-semibold text-2xl mt-4"> Thank you for participating! </P>
			<A
				:to="ROUTES.TRIALS"
				class="mt-4 mx-auto"
			>
				Start
			</A>
		</div>
	</Section>
</template>
